### ISSUE TITLE
run_etl_toolkit_tool_as_i2_etl - where do I execute this script to create/manage and InformationStore schema?

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-deployment-tooling#44]
### Background
I've successfully created external gateways so now I'm trying to establish some Information Store imports.

Using analyze-deployment-tooling 3.0.1.

As I understand it from the documentation, https://i2group.github.io/analyze-deployment-tooling/content/tools-and-functions/etl_tools.html#create-information-store-staging-table, I would use a command something like the following to create a staging table for eg a person.

![image](https://github.com/user-attachments/assets/dc0e0b7a-8eb6-414d-949e-08915acd7936)

### Issue
Apparently, the script doesn't exist as per error message in the image above.

Clicking on this link, https://i2group.github.io/analyze-deployment-tooling/content/tools-and-functions/client_functions.md#run_etl_toolkit_tool_as_i2_etl, - as mentioned in the documentation, see below, also leads to a 404.
![image](https://github.com/user-attachments/assets/2d9928b0-7fea-4f2f-b04a-010d134b1928)

There is documentation on how to create an ephemeral ETL client here: https://i2group.github.io/analyze-deployment-tooling/content/images-and-containers/etl_client.html but again when I try to run
docker build -t "etlclient_redhat:4.4.4" "images/etl_client" \
    --build-arg BASE_IMAGE="i2a_tools_redhat:4.4.4"

It won't work as I don't know where images/etl_client is in my install media.
Any tips appreciated.

**Comment by Ariana-Hlavaty-i2** [comment]
Hi @bohdanszymanik,

Your links point to our Reference Architecture. In order to use this you would have need to install the Pre-Prod Deployment as per the instructions at https://i2group.github.io/analyze-deployment-tooling/content/reference-architecture/understanding.html#how-to-use-the-reference-architecture. After this installation, you will find the missing images folder and the functions you reference above.

If instead you are using the config dev environment, then the instructions to add data to your environment can be found at https://i2group.github.io/analyze-deployment-tooling/content/add_data_config_dev.html


Hope these links help.

Regards,
Ariana

**Comment by bohdanszymanik** [comment]
Thanks Ariana - looks like I have bit to read up. I'll open a new issue if I come across anything.
